### ISSUE TITLE
The command "cactus_consolidated" encountered an error 

### ISSUE THREAD

**Issue by zhangyixing3** [HFzzzzzzz/ACMGA#2]
Hi， dear sir. I ran the ACMGA  with Arabidopsis thaliana, but it encountered an error at step cactus_consolidated. Can you help me figure out the reason behind this?
```
$  cactus_consolidated --sequences " Arabidopsis_thaliana.protein ./data/Arabidopsis/Arabidopsis_thaliana.protein.sanitized.fa An-1.protein ./data/Arabidopsis/An-1.protein.sanitized.fa Cvi.protein ./data/Arabidopsis/Cvi.protein.sanitized.fa Ler.protein ./data/Arabidopsis/Ler.protein.sanitized.fa "  --speciesTree  " (Ler.protein:0.00493038,(Cvi.protein:0.0145906,(Arabidopsis_thaliana.protein:0.0117518,An-1.protein:0.00833626)N2:0.0070939)N1:0.00493038)N0;" --logLevel DEBUG --alignments  ./data/Arabidopsis/N2_primary.paf   --params ./workflow/envs/cactus_progressive_config.xml --outputFile ./data/Arabidopsis/N2.c2h  --outputHalFastaFile ./data/Arabidopsis/N2.c2h.fa --outputReferenceFile ./data/Arabidopsis/N2.ref --outgroupEvents Ler.protein Cvi.protein --referenceEvent N2 --t 36 --secondaryAlignments ./data/Arabidopsis/N2_secondary.paf
Params file: ./workflow/envs/cactus_progressive_config.xml
Output file string : ./data/Arabidopsis/N2.c2h
Output hal fasta file string : ./data/Arabidopsis/N2.c2h.fa
Output reference fasta file string : ./data/Arabidopsis/N2.ref
Sequence files and events:  Arabidopsis_thaliana.protein ./data/Arabidopsis/Arabidopsis_thaliana.protein.sanitized.fa An-1.protein ./data/Arabidopsis/An-1.protein.sanitized.fa Cvi.protein ./data/Arabidopsis/Cvi.protein.sanitized.fa Ler.protein ./data/Arabidopsis/Ler.protein.sanitized.fa 
Alignments file: ./data/Arabidopsis/N2_primary.paf
Secondary alignments file: ./data/Arabidopsis/N2_secondary.paf
Constraint alignments file: (null)
Species tree:  (Ler.protein:0.00493038,(Cvi.protein:0.0145906,(Arabidopsis_thaliana.protein:0.0117518,An-1.protein:0.00833626)N2:0.0070939)N1:0.00493038)N0;
Outgroup events: Ler.protein
Reference event: N2
Loaded the parameters files, 0 seconds have elapsed
Set up the cactus disk, 0 seconds have elapsed
Constructed the first flower
Going to build the event tree with newick string:  (Ler.protein:0.00493038,(Cvi.protein:0.0145906,(Arabidopsis_thaliana.protein:0.0117518,An-1.protein:0.00833626)N2:0.0070939)N1:0.00493038)N0;
Parsed the tree
Constructed the basic event tree
Assigning sequence ./data/Arabidopsis/Arabidopsis_thaliana.protein.sanitized.fa to Arabidopsis_thaliana.protein
Processing file: ./data/Arabidopsis/Arabidopsis_thaliana.protein.sanitized.fa
The file ./data/Arabidopsis/Arabidopsis_thaliana.protein.sanitized.fa is specified incomplete, the sequences will not be attached
Assigning sequence ./data/Arabidopsis/An-1.protein.sanitized.fa to An-1.protein
Processing file: ./data/Arabidopsis/An-1.protein.sanitized.fa
The file ./data/Arabidopsis/An-1.protein.sanitized.fa is specified incomplete, the sequences will not be attached
Assigning sequence ./data/Arabidopsis/Cvi.protein.sanitized.fa to Cvi.protein
Processing file: ./data/Arabidopsis/Cvi.protein.sanitized.fa
The file ./data/Arabidopsis/Cvi.protein.sanitized.fa is specified incomplete, the sequences will not be attached
Assigning sequence ./data/Arabidopsis/Ler.protein.sanitized.fa to Ler.protein
Processing file: ./data/Arabidopsis/Ler.protein.sanitized.fa
The file ./data/Arabidopsis/Ler.protein.sanitized.fa is specified incomplete, the sequences will not be attached
Constructed the initial flower with 20 sequences and 8 events with string: ((Ler.protein:0.00493038,(Cvi.protein:0.0145906,(Arabidopsis_thaliana.protein:0.0117518,An-1.protein:0.00833626)N2:0.0070939)N1:0.00493038)N0:9.22337e+18)ROOT:9.22337e+18;
Established the first Flower in the hierarchy, 4 seconds have elapsed
Set up the flower disk and built hash
Opened files for writing
Finished converting alignments
Set up the flower disk and built hash
Opened files for writing
Finished converting alignments
Converted alignment coordinates, 4 seconds have elapsed
Stripped any unique IDs, 4 seconds have elapsed
ERROR: Cactus XML param node name annealingRounds not found
[0x45e39a]
[0x451e2e]
[0x45233a]
[0x41a7f3]
[0x402b81]
[0x63302a]
[0x6348c7]
[0x4060a5]
ERROR: ERROR: Failed to get string from cactus XML
```
```
$ seqkit seq -n An-1.protein.sanitized.fa  Arabidopsis_thaliana.protein.sanitized.fa  Cvi.protein.sanitized.fa  Ler.protein.sanitized.fa
id=An-1.protein|chr1
id=An-1.protein|chr2
id=An-1.protein|chr3
id=An-1.protein|chr4
id=An-1.protein|chr5
id=Arabidopsis_thaliana.protein|chr1
id=Arabidopsis_thaliana.protein|chr2
id=Arabidopsis_thaliana.protein|chr3
id=Arabidopsis_thaliana.protein|chr4
id=Arabidopsis_thaliana.protein|chr5
id=Cvi.protein|chr1
id=Cvi.protein|chr2
id=Cvi.protein|chr3
id=Cvi.protein|chr4
id=Cvi.protein|chr5
id=Ler.protein|chr1
id=Ler.protein|chr2
id=Ler.protein|chr3
id=Ler.protein|chr4
id=Ler.protein|chr5
```

**Comment by HFzzzzzzz** [comment]
> Hi， dear sir. I ran the ACMGA with Arabidopsis thaliana, but it encountered an error at step cactus_consolidated. Can you help me figure out the reason behind this?
> 
> ```
> $  cactus_consolidated --sequences " Arabidopsis_thaliana.protein ./data/Arabidopsis/Arabidopsis_thaliana.protein.sanitized.fa An-1.protein ./data/Arabidopsis/An-1.protein.sanitized.fa Cvi.protein ./data/Arabidopsis/Cvi.protein.sanitized.fa Ler.protein ./data/Arabidopsis/Ler.protein.sanitized.fa "  --speciesTree  " (Ler.protein:0.00493038,(Cvi.protein:0.0145906,(Arabidopsis_thaliana.protein:0.0117518,An-1.protein:0.00833626)N2:0.0070939)N1:0.00493038)N0;" --logLevel DEBUG --alignments  ./data/Arabidopsis/N2_primary.paf   --params ./workflow/envs/cactus_progressive_config.xml --outputFile ./data/Arabidopsis/N2.c2h  --outputHalFastaFile ./data/Arabidopsis/N2.c2h.fa --outputReferenceFile ./data/Arabidopsis/N2.ref --outgroupEvents Ler.protein Cvi.protein --referenceEvent N2 --t 36 --secondaryAlignments ./data/Arabidopsis/N2_secondary.paf
> Params file: ./workflow/envs/cactus_progressive_config.xml
> Output file string : ./data/Arabidopsis/N2.c2h
> Output hal fasta file string : ./data/Arabidopsis/N2.c2h.fa
> Output reference fasta file string : ./data/Arabidopsis/N2.ref
> Sequence files and events:  Arabidopsis_thaliana.protein ./data/Arabidopsis/Arabidopsis_thaliana.protein.sanitized.fa An-1.protein ./data/Arabidopsis/An-1.protein.sanitized.fa Cvi.protein ./data/Arabidopsis/Cvi.protein.sanitized.fa Ler.protein ./data/Arabidopsis/Ler.protein.sanitized.fa 
> Alignments file: ./data/Arabidopsis/N2_primary.paf
> Secondary alignments file: ./data/Arabidopsis/N2_secondary.paf
> Constraint alignments file: (null)
> Species tree:  (Ler.protein:0.00493038,(Cvi.protein:0.0145906,(Arabidopsis_thaliana.protein:0.0117518,An-1.protein:0.00833626)N2:0.0070939)N1:0.00493038)N0;
> Outgroup events: Ler.protein
> Reference event: N2
> Loaded the parameters files, 0 seconds have elapsed
> Set up the cactus disk, 0 seconds have elapsed
> Constructed the first flower
> Going to build the event tree with newick string:  (Ler.protein:0.00493038,(Cvi.protein:0.0145906,(Arabidopsis_thaliana.protein:0.0117518,An-1.protein:0.00833626)N2:0.0070939)N1:0.00493038)N0;
> Parsed the tree
> Constructed the basic event tree
> Assigning sequence ./data/Arabidopsis/Arabidopsis_thaliana.protein.sanitized.fa to Arabidopsis_thaliana.protein
> Processing file: ./data/Arabidopsis/Arabidopsis_thaliana.protein.sanitized.fa
> The file ./data/Arabidopsis/Arabidopsis_thaliana.protein.sanitized.fa is specified incomplete, the sequences will not be attached
> Assigning sequence ./data/Arabidopsis/An-1.protein.sanitized.fa to An-1.protein
> Processing file: ./data/Arabidopsis/An-1.protein.sanitized.fa
> The file ./data/Arabidopsis/An-1.protein.sanitized.fa is specified incomplete, the sequences will not be attached
> Assigning sequence ./data/Arabidopsis/Cvi.protein.sanitized.fa to Cvi.protein
> Processing file: ./data/Arabidopsis/Cvi.protein.sanitized.fa
> The file ./data/Arabidopsis/Cvi.protein.sanitized.fa is specified incomplete, the sequences will not be attached
> Assigning sequence ./data/Arabidopsis/Ler.protein.sanitized.fa to Ler.protein
> Processing file: ./data/Arabidopsis/Ler.protein.sanitized.fa
> The file ./data/Arabidopsis/Ler.protein.sanitized.fa is specified incomplete, the sequences will not be attached
> Constructed the initial flower with 20 sequences and 8 events with string: ((Ler.protein:0.00493038,(Cvi.protein:0.0145906,(Arabidopsis_thaliana.protein:0.0117518,An-1.protein:0.00833626)N2:0.0070939)N1:0.00493038)N0:9.22337e+18)ROOT:9.22337e+18;
> Established the first Flower in the hierarchy, 4 seconds have elapsed
> Set up the flower disk and built hash
> Opened files for writing
> Finished converting alignments
> Set up the flower disk and built hash
> Opened files for writing
> Finished converting alignments
> Converted alignment coordinates, 4 seconds have elapsed
> Stripped any unique IDs, 4 seconds have elapsed
> ERROR: Cactus XML param node name annealingRounds not found
> [0x45e39a]
> [0x451e2e]
> [0x45233a]
> [0x41a7f3]
> [0x402b81]
> [0x63302a]
> [0x6348c7]
> [0x4060a5]
> ERROR: ERROR: Failed to get string from cactus XML
> ```
> 
> ```
> $ seqkit seq -n An-1.protein.sanitized.fa  Arabidopsis_thaliana.protein.sanitized.fa  Cvi.protein.sanitized.fa  Ler.protein.sanitized.fa
> id=An-1.protein|chr1
> id=An-1.protein|chr2
> id=An-1.protein|chr3
> id=An-1.protein|chr4
> id=An-1.protein|chr5
> id=Arabidopsis_thaliana.protein|chr1
> id=Arabidopsis_thaliana.protein|chr2
> id=Arabidopsis_thaliana.protein|chr3
> id=Arabidopsis_thaliana.protein|chr4
> id=Arabidopsis_thaliana.protein|chr5
> id=Cvi.protein|chr1
> id=Cvi.protein|chr2
> id=Cvi.protein|chr3
> id=Cvi.protein|chr4
> id=Cvi.protein|chr5
> id=Ler.protein|chr1
> id=Ler.protein|chr2
> id=Ler.protein|chr3
> id=Ler.protein|chr4
> id=Ler.protein|chr5
> ```
Hi,dear sir.
It looks like you are running it locally. This requires modifying some running paths so that each software can run with correct results. You have given me relatively little information now. You have provided the paf file in the subtree/ directory and the log file in the ACMGA/ directory.

**Comment by zhangyixing3** [comment]
Could you  share your cactus_progressive_config.xml file from the test data? I am not familiar with cactus and have been unable to find information about cactus_progressive_config.xml.

**Comment by zhangyixing3** [comment]
Thanks , I've encountered another issue.  Combine all the CDS sequences into a file named nonDuplicateCDS. However,  I think a single comprehensive CDS sequence would be enough for gene prediction .

**Comment by HFzzzzzzz** [comment]
> Thanks , I've encountered another issue. Combine all the CDS sequences into a file named nonDuplicateCDS. However, I think a single comprehensive CDS sequence would be enough for gene prediction .

Yes, theoretically a single CDS can predict. We are currently optimizing this area, which will speed up subsequent pair-wise genome alignment. Not using a single CDS, but reducing the size of the CDS as much as possible.

**Comment by zhangyixing3** [comment]
Thank you again!

**Comment by conniecl** [comment]
@zhangyixing3 
Have you solved the problem? `ERROR: Cactus XML param node name annealingRounds not found`, same error had occurred when I used the example file and ran locally, without docker
