### ISSUE TITLE
anchorwave Assertion `temp.compare(queryGenomeSequence) == 0' failed.  

### ISSUE THREAD

**Issue by zhangyixing3** [HFzzzzzzz/ACMGA#5]
Hi, I  encounter an issue with  anchorwave
**command**
```
anchorwave proali -i ./data/N12.gff3 -as ./data/N12_cds.fa -r ./data/N12.ref -a ./data/N13_N12_cds.sam -ar ./data/N12_N12_ref.sam -s ./data/N13.ref -n ./data/N12_N13.anchors -o ./data/N12_N13.anchorwave.maf -f ./data/N12_N13.anchorwave.f.maf -Q 1 -R 1 -t 10 > N12_N13.log 2>&1
```
Error message
anchorwave: AnchorWave/src/impl/deNovoGenomeVariantCallingMultipleThreads.cpp:193: void genomeAlignmentSingleThread(std::vector<AlignmentMatch>, bool, bool, std::ofstream&, std::ofstream&, std::map<std::__cxx11::basic_string<char>, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, long int, long int, int> >&, std::map<std::__cxx11::basic_string<char>, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, long int, long int, int> >&, int, std::string, std::string, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, std::atomic_int&): Assertion `temp.compare(queryGenomeSequence) == 0' failed

**Then   I check the length of the sequence.Some of the sequences are too short ？**
```
$ le ./data/N12.ref.fai | cut -f 1,2 | sort -k2,2n | head
N12refChr137	1
N12refChr95	1
N12refChr97	1
N12refChr53	2
N12refChr9	2
N12refChr91	3
N12refChr56	7
N12refChr20	10
N12refChr132	27
N12refChr96	32
$ le ./data/N13.ref.fai | cut -f 1,2 | sort -k2,2n | head
N13refChr46	1
N13refChr26	3
N13refChr49	14
N13refChr50	15
N13refChr70	16
N13refChr39	19
N13refChr33	30
N13refChr66	73
N13refChr34	102
N13refChr76	109
```
How can I resolve this issue?

**Comment by HFzzzzzzz** [comment]
> Hi, I encounter an issue with anchorwave **command**
> 
> ```
> anchorwave proali -i ./data/N12.gff3 -as ./data/N12_cds.fa -r ./data/N12.ref -a ./data/N13_N12_cds.sam -ar ./data/N12_N12_ref.sam -s ./data/N13.ref -n ./data/N12_N13.anchors -o ./data/N12_N13.anchorwave.maf -f ./data/N12_N13.anchorwave.f.maf -Q 1 -R 1 -t 10 > N12_N13.log 2>&1
> ```
> 
> Error message anchorwave: AnchorWave/src/impl/deNovoGenomeVariantCallingMultipleThreads.cpp:193: void genomeAlignmentSingleThread(std::vector, bool, bool, std::ofstream&, std::ofstream&, std::map<std::__cxx11::basic_string, std::tuple<std::__cxx11::basic_string<char, std::char_traits, std::allocator >, long int, long int, int> >&, std::map<std::__cxx11::basic_string, std::tuple<std::__cxx11::basic_string<char, std::char_traits, std::allocator >, long int, long int, int> >&, int, std::string, std::string, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, std::atomic_int&): Assertion `temp.compare(queryGenomeSequence) == 0' failed
> 
> **Then I check the length of the sequence.Some of the sequences are too short ？**
> 
> ```
> $ le ./data/N12.ref.fai | cut -f 1,2 | sort -k2,2n | head
> N12refChr137	1
> N12refChr95	1
> N12refChr97	1
> N12refChr53	2
> N12refChr9	2
> N12refChr91	3
> N12refChr56	7
> N12refChr20	10
> N12refChr132	27
> N12refChr96	32
> $ le ./data/N13.ref.fai | cut -f 1,2 | sort -k2,2n | head
> N13refChr46	1
> N13refChr26	3
> N13refChr49	14
> N13refChr50	15
> N13refChr70	16
> N13refChr39	19
> N13refChr33	30
> N13refChr66	73
> N13refChr34	102
> N13refChr76	109
> ```
> 
> How can I resolve this issue?

Hello, was the CDS sequence you obtained generated according to our customized script? I need more information to determine the problem (including more command lines and its input files)

**Comment by zhangyixing3** [comment]
Can I add you on WeChat? Or you add me (Wechat 17358077597 )  , and then I  send you the data later ? My genome is small.

**Comment by HFzzzzzzz** [comment]
> Can I add you on WeChat? Or you add me (Wechat 17358077597 ) , and then I send you the data later ? My genome is small.

A similar problem occurred. This may be a memory problem, and more information is needed to troubleshoot. https://github.com/baoxingsong/AnchorWave/issues/24

**Comment by zhangyixing3** [comment]
This may be a memory problem.
